repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.730'
  hooks:
  - id: mypy
    args: [
      --config-file=./mypy.ini
      # --python-version=3.7,
      # --warn-return-any,
      # --warn-unused-configs,
      # --disallow-untyped-defs,
      # --ignore-missing-imports,
    ]
